### ISSUE TITLE
BUG: Nolok boss level doesn't load when exported on Linux

### ISSUE THREAD

**Issue by ztianyang** [Alzter/SuperTux-Classic#10]
**SuperTux Classic version:** Latest commit
**System information:** Ubuntu 22.04
**Describe the bug**
When you export SuperTux Classic on Linux, the Nolok boss level doesn't load.

**To Reproduce**
1. Git clone the project and export it with Godot 3.5.2 on Linux.
2. Open the game and go to the level dot where the Nolok boss level is.
3. The level name is not displayed.
    ![Screenshot from 2023-04-30 20-24-42](https://user-images.githubusercontent.com/59285502/235399072-dbfbf7d9-34e5-4700-a147-0ad4fb49cf65.png)
4. When you try to enter the level, the game shows a gray screen.
    ![Screenshot from 2023-04-30 20-27-03](https://user-images.githubusercontent.com/59285502/235399740-9f709e7a-f388-4b8b-8f5a-80ae4c8e6049.png)

[error.txt](https://github.com/Alzter/SuperTux-Classic/files/11363356/error.txt)

**Expected behavior**
The level name should be displayed on the worldmap and the level should load.

**Comment by Alzter** [comment]
@ztianyang Can you please test this bug on the latest commit and confirm if it still occurs?

**Comment by ztianyang** [comment]
It still occurs on the latest commit.

According to the error, the level is trying to load the file `level27script.gd`, but the filename is actually `Level27Script.gd`. Filenames are case sensitive on Linux, so the file fails to load.

Renaming the file to `level27script.gd` or changing `level27script.gd` to `Level27Script.gd` in https://github.com/Alzter/SuperTux-Classic/blob/7de0b4ebbb39d06a954fb528bf0352270d7e554d/SourceCode/scenes/levels/world1/level27.tscn#L10 solves the issue for me.

**Comment by Alzter** [comment]
Fixed
