### ISSUE TITLE
BUG: Tux gets stuck on landscape mode for mobile HTML5 version when levels use Water background/foreground node

### ISSUE THREAD

**Issue by Mal0gen** [Alzter/SuperTux-Classic#11]
**SuperTux Classic version:** Web Version on itch.io
**System information:** Safari (iOS 16.4.1)

**Describe the bug**
Upon entering Stone Cold/A Somewhat Smaller Bathtub in Landscape mode, Tux is frozen in place and unable to move, playing the jumping sprite and only being able to change by going left or right (without moving).
Upon rotating my phone to Portrait mode, the problem disappears and I can move like normal.

**To Reproduce**
1. Enter any of those levels in Landscape mode.

**Expected behavior**
Tux being unable to move and playing the jumping sprite.

**Comment by Alzter** [comment]
This issue occurred due to the water background/foreground objects in levels erroneously having solid collision layers, which would have their hitbox extend when the phone was in landscape mode, thereby trapping Tux. I believe it has been fixed now, can you check this @Mal0gen ?

**Comment by Alzter** [comment]
I think this is fixed. @Mal0gen if this bug persists, please reopen the issue
