### ISSUE TITLE
BUG: Cannot save and quit after Tux dies in level editor

### ISSUE THREAD

**Issue by ztianyang** [Alzter/SuperTux-Classic#12]
**SuperTux Classic version:** Commit cec260f
**System information:** Ubuntu 22.04

**Describe the bug**
After Tux dies in level editor, the pause menu no longer shows up when pressing the escape key, which means that the level cannot be saved.

**To Reproduce**
1. Open a level in the level editor.
2. Press escape key to make sure that the pause menu works.
3. Play the level and make Tux die in the level editor.
4. Press the escape key again and see that the pause menu no longer shows up.

**Expected behavior**
The pause menu should always show up when pressing the escape key in the level editor.

**Comment by Alzter** [comment]
Fixed! This happened because the global variable, **can_pause**, is set to false when Tux dies, and was not being set back to true when the Level Editor re-appeared.
