### ISSUE TITLE
BUG: Game crashes during Grumbel Death sequence

### ISSUE THREAD

**Issue by Tlaloc1** [Alzter/SuperTux-Classic#13]
**SuperTux Classic version:** STC 0.3.5
**System information:** Windows, Android

**Describe the bug**
During Grumbel's death sequence, the game crashes if either the game gets paused or if Tux hits the boss during the sequence

**To Reproduce**
Steps to reproduce pause crash:
1) Pause the game during Grumbels death sequence
2) The game will crash
Expected: Game to pause / input to be ignored
Steps to reproduce hit crash:
1) During the death sequence, move Tux to land on Grumbel
2) The game will crash
Expected: sequence to continue as normal

**Comment by Alzter** [comment]
Fixed. fc14a798189f033c63b9a637decd7b5b476c96cc
