### ISSUE TITLE
BUG: Tobgle Road liquid layer issues

### ISSUE THREAD

**Issue by tulpenkiste** [Alzter/SuperTux-Classic#18]
**SuperTux Classic version:** 0.4.0 (including #16)
**System information:** Linux with kernel version 6.3.7-arch1-1 x86_64

**Describe the bug**
Liquid layer has incorrect z order and is displaying over ice tiles

**Expected behaviour**
Layering should work as intended and look normal.

**Actual behaviour**
![image](https://github.com/Alzter/SuperTux-Classic/assets/63363329/0fc9fe0b-d431-402b-b90e-282023191010)

![image](https://github.com/Alzter/SuperTux-Classic/assets/63363329/44f25e20-c4e9-48fb-b913-213fff8e6917)

**Comment by Alzter** [comment]
No, this is intentional. The original level does this.
